language: python
install:
- pip install -r requirements.txt
script:
- mkdocs build --verbose --clean --strict
deploy:
  provider: pages
  local-dir: site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
